// <auto-generated />
using MaatjesProjectV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace MaatjesProjectV2.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20171007110353_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Dementing");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("WheelChair");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.PersonInterest", b =>
                {
                    b.Property<int>("PersonId");

                    b.Property<int>("InterestId");

                    b.HasKey("PersonId", "InterestId");

                    b.HasIndex("InterestId");

                    b.ToTable("PersonInterests");
                });

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.ElderlyPerson", b =>
                {
                    b.HasBaseType("MaatjesProjectMVC.Models.MemberViewModels.Person");

                    b.Property<string>("City");

                    b.Property<string>("Department");

                    b.ToTable("ElderlyPerson");

                    b.HasDiscriminator().HasValue("ElderlyPerson");
                });

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.Volunteer", b =>
                {
                    b.HasBaseType("MaatjesProjectMVC.Models.MemberViewModels.Person");


                    b.ToTable("Volunteer");

                    b.HasDiscriminator().HasValue("Volunteer");
                });

            modelBuilder.Entity("MaatjesProjectMVC.Models.MemberViewModels.PersonInterest", b =>
                {
                    b.HasOne("MaatjesProjectMVC.Models.MemberViewModels.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaatjesProjectMVC.Models.MemberViewModels.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
